### ISSUE TITLE
'Namespace' object has no attribute 'key'

### ISSUE THREAD

**Issue by magaya** [adrg/lsbsteg#1]
After i run the file in the terminal It started to show the error 

'Namespace' object has no attribute 'key'

How can i override this?

**Comment by adrg** [comment]
Hi there

I've fixed the issue. I did not test in an environment which didn't have encryption libraries installed.
Please pull the script and try it now.

**Comment by magaya** [comment]
Thanks for the feedback, I was able to override this by installing
 "Pycryptodome" since pycrypto would show a c++ error.

The encryption isn't working still but at least the embedding if now
possible.

Thanks
